<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="${report.id == 0 ? 'Create Report' : 'Edit Report'}" scope="request"/>
<jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="page-actions"><div><a href="${pageContext.request.contextPath}/reports/manage" class="small"><i class="bi bi-arrow-left"></i> Saved reports</a><h1 class="page-heading mt-3"><c:out value="${pageTitle}"/></h1><p>Save a date range and filters for your operations review.</p></div></div>
<div class="report-form-layout"><form method="post" action="${pageContext.request.contextPath}/reports/manage" class="panel needs-validation" novalidate>
<c:if test="${not empty formError}"><div class="alert alert-danger" role="alert"><c:out value="${formError}"/></div></c:if>
<input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="${report.id}">
<h2 class="h5 mb-4">Report details</h2>
<div class="mb-4"><label class="form-label" for="title">Report title</label><input class="form-control" id="title" name="title" required maxlength="120" value="<c:out value='${report.title}'/>" placeholder="Monthly operations review"><div class="invalid-feedback">Enter a report title.</div></div>
<div class="row g-3 mb-4"><div class="col-sm-6"><label class="form-label" for="fromDate">Start date</label><input class="form-control" type="date" id="fromDate" name="fromDate" required value="<c:out value='${report.fromDate}'/>"></div><div class="col-sm-6"><label class="form-label" for="toDate">End date</label><input class="form-control" type="date" id="toDate" name="toDate" data-after="fromDate" required value="<c:out value='${report.toDate}'/>"><div class="invalid-feedback">End date must be on or after start date.</div></div></div>
<div class="mb-4"><label class="form-label" for="orderStatus">Order status</label><select class="form-select" name="orderStatus" id="orderStatus"><option value="">All statuses</option><c:forEach items="${statuses}" var="status"><option value="${status}" ${report.orderStatus == status ? 'selected' : ''}><c:out value="${status}"/></option></c:forEach></select></div>
<div class="mb-4"><label class="form-label" for="notes">Notes <span class="text-secondary fw-normal">(optional)</span></label><textarea class="form-control" rows="5" id="notes" name="notes" maxlength="2000"><c:out value="${report.notes}"/></textarea><small class="text-secondary"><span data-char-count>0</span> / 2000</small></div>
<div class="d-flex gap-2 border-top pt-4"><button class="btn btn-primary" type="submit"><span class="spinner-border spinner-border-sm d-none" aria-hidden="true"></span> <span class="button-label">Save report</span></button><a class="btn btn-light" href="${pageContext.request.contextPath}/reports/manage">Cancel</a></div>
</form><aside class="report-context"><i class="bi bi-file-earmark-bar-graph fs-2 text-primary"></i><h2 class="h5 mt-3">Live report</h2><p>Saved reports use the latest database records when opened, not a historical snapshot.</p><p>The date range applies to orders, service popularity, inventory usage and deliveries. Order status filters the order table. Overview metrics and charts keep their labelled periods.</p></aside></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
