<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="editing" value="${not empty delivery.id}"/><c:set var="pageTitle" value="${editing?'Edit Pickup & Delivery':'Schedule Pickup & Delivery'}" scope="request"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="page-actions"><div><h1 class="page-heading"><c:out value="${pageTitle}"/></h1><p>Connect a laundry order to its collection and return journey.</p></div><a class="btn btn-light" href="${pageContext.request.contextPath}/deliveries/">Back</a></div>
<div class="panel form-panel"><form method="post" action="${pageContext.request.contextPath}/deliveries/" class="needs-validation" novalidate><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="action" value="${editing?'update':'create'}"><c:if test="${editing}"><input type="hidden" name="id" value="${delivery.id}"></c:if><div class="form-section"><h2>Schedule</h2><div class="row g-3">
<div class="col-md-6"><label class="form-label">Laundry order *</label><select class="form-select" name="orderId" required><option value="">Select order</option><c:forEach items="${orders}" var="order"><option value="${order.id}" ${delivery.orderId==order.id?'selected':''}><c:out value="${order.orderNumber}"/> — <c:out value="${order.customerName}"/></option></c:forEach></select></div><div class="col-md-6"><label class="form-label">Coordinator</label><select class="form-select" name="coordinatorId"><option value="">Unassigned</option><c:forEach items="${coordinators}" var="user"><option value="${user.id}" ${delivery.coordinatorId==user.id?'selected':''}><c:out value="${user.fullName}"/></option></c:forEach></select></div>
<div class="col-md-6"><label class="form-label">Pickup date & time</label><input class="form-control" name="pickupAt" type="datetime-local" value="<c:out value='${delivery.pickupAt}'/>"></div><div class="col-md-6"><label class="form-label">Delivery date & time</label><input class="form-control" name="deliveryAt" type="datetime-local" value="<c:out value='${delivery.deliveryAt}'/>" data-after-datetime="pickupAt"></div>
<div class="col-md-6"><label class="form-label">Pickup address *</label><textarea class="form-control" name="pickupAddress" rows="3" maxlength="300" required><c:out value="${delivery.pickupAddress}"/></textarea></div><div class="col-md-6"><label class="form-label">Delivery address *</label><textarea class="form-control" name="deliveryAddress" rows="3" maxlength="300" required><c:out value="${delivery.deliveryAddress}"/></textarea></div>
<div class="col-md-6"><label class="form-label">Status *</label><select class="form-select" name="status" required><c:forEach items="${['REQUESTED','SCHEDULED','PICKED_UP','PROCESSING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED']}" var="status"><option value="${status}" ${delivery.status==status || (empty delivery.status && status=='REQUESTED')?'selected':''}><c:out value="${status}"/></option></c:forEach></select></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2" maxlength="500"><c:out value="${delivery.notes}"/></textarea></div>
</div></div><div class="form-actions"><a class="btn btn-light" href="${pageContext.request.contextPath}/deliveries/">Cancel</a><button class="btn btn-primary">${editing?'Save changes':'Create request'}</button></div></form></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
