<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="editing" value="${not empty item.id}"/><c:set var="pageTitle" value="${editing?'Edit Inventory Item':'Add Inventory Item'}" scope="request"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="page-actions"><div><h1 class="page-heading"><c:out value="${pageTitle}"/></h1><p>Maintain accurate supply and reorder information.</p></div><a class="btn btn-light" href="${pageContext.request.contextPath}/inventory/">Back</a></div>
<div class="panel form-panel"><form method="post" action="${pageContext.request.contextPath}/inventory/" class="needs-validation" novalidate><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="action" value="${editing?'update':'create'}"><c:if test="${editing}"><input type="hidden" name="id" value="${item.id}"></c:if><div class="form-section"><h2>Item information</h2><div class="row g-3">
<div class="col-md-6"><label class="form-label">Item name *</label><input class="form-control" name="itemName" value="<c:out value='${item.itemName}'/>" maxlength="120" required></div><div class="col-md-6"><label class="form-label">Category *</label><input class="form-control" name="category" value="<c:out value='${item.category}'/>" maxlength="80" placeholder="e.g. Cleaning Chemical" required></div>
<c:if test="${!editing}"><div class="col-md-4"><label class="form-label">Opening quantity *</label><input class="form-control" name="quantity" type="number" min="0" step="0.01" value="0" required></div></c:if><div class="col-md-4"><label class="form-label">Unit *</label><input class="form-control" name="unit" value="<c:out value='${item.unit}'/>" maxlength="30" placeholder="Litres, Pieces, Kg" required></div><div class="col-md-4"><label class="form-label">Reorder level *</label><input class="form-control" name="reorderLevel" type="number" min="0" step="0.01" value="<c:out value='${item.reorderLevel}'/>" required></div>
<div class="col-md-6"><label class="form-label">Unit price (LKR) *</label><input class="form-control" name="unitPrice" type="number" min="0" step="0.01" value="<c:out value='${item.unitPrice}'/>" required></div><div class="col-md-6"><label class="form-label">Supplier</label><input class="form-control" name="supplier" value="<c:out value='${item.supplier}'/>" maxlength="150"></div><c:if test="${editing}"><div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="ACTIVE" ${item.status=='ACTIVE'?'selected':''}>Active</option><option value="INACTIVE" ${item.status=='INACTIVE'?'selected':''}>Inactive</option></select></div></c:if>
</div></div><div class="form-actions"><a class="btn btn-light" href="${pageContext.request.contextPath}/inventory/">Cancel</a><button class="btn btn-primary">${editing?'Save changes':'Add item'}</button></div></form></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
