<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<c:set var="pageTitle" value="Order Management" scope="request"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="page-actions"><div><h1 class="page-heading">Laundry orders</h1><p>Create, find and track every laundry order.</p></div><c:if test="${sessionScope.role=='ADMINISTRATOR'||sessionScope.role=='RECEPTIONIST'}"><a class="btn btn-primary" href="${pageContext.request.contextPath}/orders/new"><i class="bi bi-plus-lg"></i> New order</a></c:if></div>
<div class="panel">
<form class="filter-bar flex-wrap" method="get" action="${pageContext.request.contextPath}/orders/">
    <div class="search-field"><i class="bi bi-search"></i><input class="form-control" name="search" value="<c:out value='${param.search}'/>" placeholder="Order number or customer"></div>
    <select class="form-select" name="status"><option value="">All statuses</option><c:forEach items="${['RECEIVED','WASHING','PROCESSING','READY','COMPLETED','DELIVERED','CANCELLED']}" var="status"><option value="${status}" ${param.status==status?'selected':''}><c:out value="${status}"/></option></c:forEach></select>
    <input class="form-control" type="date" name="from" value="<c:out value='${param.from}'/>" title="From date"><input class="form-control" type="date" name="to" value="<c:out value='${param.to}'/>" title="To date"><button class="btn btn-outline-primary">Filter</button><a class="btn btn-light" href="${pageContext.request.contextPath}/orders/">Reset</a>
</form>
<c:choose><c:when test="${empty orders}"><div class="empty-state"><i class="bi bi-basket2"></i><h3>No orders found</h3><p>Adjust the filters or create a new laundry order.</p></div></c:when><c:otherwise><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Order</th><th>Customer</th><th>Received</th><th>Expected</th><th>Status</th><th>Total</th><th class="text-end">Actions</th></tr></thead><tbody>
<c:forEach items="${orders}" var="order"><tr><td><strong><c:out value="${order.orderNumber}"/></strong></td><td><c:out value="${order.customerName}"/></td><td><c:out value="${order.receivedAt.toLocalDate()}"/></td><td><c:out value="${order.expectedCompletionDate}"/></td><td><span class="status-badge" data-status="${order.status}"><c:out value="${order.status}"/></span></td><td>LKR <fmt:formatNumber value="${order.totalAmount}" minFractionDigits="2"/></td><td class="text-end"><div class="btn-group"><a class="btn btn-sm btn-light" href="${pageContext.request.contextPath}/orders/view?id=${order.id}" title="View"><i class="bi bi-eye"></i></a><a class="btn btn-sm btn-light" href="${pageContext.request.contextPath}/orders/receipt?id=${order.id}" title="Receipt"><i class="bi bi-printer"></i></a><c:if test="${(sessionScope.role=='ADMINISTRATOR'||sessionScope.role=='RECEPTIONIST') && order.status!='DELIVERED' && order.status!='CANCELLED'}"><a class="btn btn-sm btn-light" href="${pageContext.request.contextPath}/orders/edit?id=${order.id}" title="Edit"><i class="bi bi-pencil"></i></a><form method="post" action="${pageContext.request.contextPath}/orders/" data-confirm="Cancel this order? This cannot be reversed."><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="id" value="${order.id}"><button class="btn btn-sm btn-light text-danger" title="Cancel"><i class="bi bi-x-circle"></i></button></form></c:if></div></td></tr></c:forEach>
</tbody></table></div></c:otherwise></c:choose></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
