<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<c:set var="pageTitle" value="Order Details" scope="request"/><jsp:include page="/WEB-INF/views/common/header.jsp"/>
<div class="page-actions"><div><div class="d-flex align-items-center gap-2"><h1 class="page-heading mb-0"><c:out value="${order.orderNumber}"/></h1><span class="status-badge" data-status="${order.status}"><c:out value="${order.status}"/></span></div><p class="mt-2">Received <c:out value="${order.receivedAt}"/></p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="${pageContext.request.contextPath}/orders/receipt?id=${order.id}"><i class="bi bi-printer"></i> Receipt</a><a class="btn btn-light" href="${pageContext.request.contextPath}/orders/">Back</a></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="panel mb-4"><div class="panel-header"><h2>Order items</h2></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Item</th><th>Service</th><th class="text-end">Qty</th><th class="text-end">Unit price</th><th class="text-end">Subtotal</th></tr></thead><tbody><c:forEach items="${order.items}" var="item"><tr><td><c:out value="${item.itemName}"/></td><td><c:out value="${item.serviceName}"/></td><td class="text-end"><c:out value="${item.quantity}"/></td><td class="text-end">LKR <fmt:formatNumber value="${item.unitPrice}" minFractionDigits="2"/></td><td class="text-end fw-semibold">LKR <fmt:formatNumber value="${item.subtotal}" minFractionDigits="2"/></td></tr></c:forEach></tbody><tfoot><tr><th colspan="4" class="text-end">Total</th><th class="text-end fs-5 text-primary">LKR <fmt:formatNumber value="${order.totalAmount}" minFractionDigits="2"/></th></tr></tfoot></table></div></div>
<div class="panel"><div class="panel-header"><h2>Progress</h2></div><div class="order-progress" data-current-status="${order.status}"><c:forEach items="${['RECEIVED','WASHING','PROCESSING','READY','COMPLETED','DELIVERED']}" var="status"><div class="progress-step" data-step="${status}"><span><i class="bi bi-check-lg"></i></span><small><c:out value="${status}"/></small></div></c:forEach></div></div></div>
<div class="col-lg-4"><div class="panel mb-4"><div class="panel-header"><h2>Details</h2></div><dl class="detail-list"><dt>Customer</dt><dd><c:out value="${order.customerName}"/></dd><dt>Expected completion</dt><dd><c:out value="${order.expectedCompletionDate}"/></dd><dt>Delivery date</dt><dd><c:out value="${empty order.deliveryDate?'Not scheduled':order.deliveryDate}"/></dd><dt>Notes</dt><dd><c:out value="${empty order.notes?'—':order.notes}"/></dd></dl></div>
<c:if test="${sessionScope.role=='ADMINISTRATOR'||sessionScope.role=='RECEPTIONIST'||sessionScope.role=='LAUNDRY_STAFF'}"><div class="panel"><div class="panel-header"><h2>Update status</h2></div><form method="post" action="${pageContext.request.contextPath}/orders/"><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="${order.id}"><select class="form-select mb-3" name="status"><c:forEach items="${['RECEIVED','WASHING','PROCESSING','READY','COMPLETED','DELIVERED','CANCELLED']}" var="status"><option value="${status}" ${order.status==status?'selected':''}><c:out value="${status}"/></option></c:forEach></select><button class="btn btn-primary w-100">Save status</button></form></div></c:if>
</div></div>
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>
